version: '3.8'

services:
  django:
    build: .
    env_file:
      - .env
    command: >
      sh -c "
      if [ ! -s .env ]; then
        echo 'SECRET_KEY=$(openssl rand -base64 64 | tr -d /=+ | head -c 50)' > .env;
      fi;
      python manage.py collectstatic --noinput;
      python manage.py migrate;
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
